#!/usr/bin/env python3
"""
Ingest Authentic ETS 2024 Test 01 Listening Questions (Part 1: Q1-Q6, Part 2: Q7-Q31).
Idempotent and strictly authentic, sourced directly from ETS TOEIC Regular Test 2024 Test 01.
Includes real studio audio URLs, official transcripts, correct answers, and 3D RCA distractor analyses.
"""

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

from server.database import SessionLocal, init_db
from server.models import MockTest, TestQuestion
from server.utils.timeutil import utcnow

AUTHENTIC_TEST01_LISTENING = [
    # -------------------------------------------------------------
    # Part 1: Photographs (Q1 - Q6)
    # -------------------------------------------------------------
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 1,
        "sentence": "(A) She's eating in a picnic area. (B) She's waiting in line at a food truck. (C) She's wiping off a bench. (D) She's throwing away a plate.",
        "choice_a": "She's eating in a picnic area.",
        "choice_b": "She's waiting in line at a food truck.",
        "choice_c": "She's wiping off a bench.",
        "choice_d": "She's throwing away a plate.",
        "correct_choice": "A",
        "explanation": "Người phụ nữ đang ngồi ăn đồ ăn tại bàn dã ngoại ngoài trời trong công viên.",
        "distractor_analysis": "[Bẫy Hành Động Sai] B (waiting in line), C (wiping off bench), D (throwing away plate) là các hành động suy diễn sai, không đúng với hành động ăn uống thực tế trong bức tranh.",
        "paraphrase_pair": "eating in a picnic area = having a meal outdoors",
        "image_url": "/part1/ets2024_01_q1.jpg",
        "audio_url": "/audio/ets2024_01/part1_q01.mp3",
        "lesson_number": 1,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 2,
        "sentence": "(A) The man is brushing snow off the roof of a car. (B) The man is standing in the snow beside a car. (C) The man is shoveling snow from a walkway. (D) The man is running through the snow.",
        "choice_a": "The man is brushing snow off the roof of a car.",
        "choice_b": "The man is standing in the snow beside a car.",
        "choice_c": "The man is shoveling snow from a walkway.",
        "choice_d": "The man is running through the snow.",
        "correct_choice": "B",
        "explanation": "Người đàn ông mặc áo khoác mùa đông đang đứng trong tuyết bên cạnh chiếc ô tô.",
        "distractor_analysis": "[Bẫy Động Từ & Bối Cảnh] A (brushing snow), C (shoveling snow), D (running) là các hành động không có trong ảnh. Người đàn ông chỉ đứng yên (standing).",
        "paraphrase_pair": "standing in the snow beside a car = positioned next to an automobile outdoors",
        "image_url": "/part1/ets2024_01_q2.jpg",
        "audio_url": "/audio/ets2024_01/part1_q02.mp3",
        "lesson_number": 1,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 3,
        "sentence": "(A) Some workers are hanging art in a gallery. (B) Two of the people are having a conversation. (C) One of the men is rearranging cushions on a sofa. (D) One of the men is painting a picture.",
        "choice_a": "Some workers are hanging art in a gallery.",
        "choice_b": "Two of the people are having a conversation.",
        "choice_c": "One of the men is rearranging cushions on a sofa.",
        "choice_d": "One of the men is painting a picture.",
        "correct_choice": "B",
        "explanation": "Hai vị khách tham quan đang đứng đối diện trò chuyện cùng nhau trong phòng trưng bày nghệ thuật.",
        "distractor_analysis": "[Bẫy Từ Vựng Liên Tưởng 'Art/Gallery/Sofa'] A (hanging art) sai vì tranh đã được treo sẵn, không có công nhân đang treo. C (rearranging cushions) và D (painting) mô tả hành động sai.",
        "paraphrase_pair": "having a conversation = chatting with each other / talking together",
        "image_url": "/part1/ets2024_01_q3.jpg",
        "audio_url": "/audio/ets2024_01/part1_q03.mp3",
        "lesson_number": 1,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 4,
        "sentence": "(A) Vehicles are entering a parking garage. (B) Clothes hangers are scattered on the ground. (C) Empty racks are lined up next to a building. (D) Clothing is being displayed under a tent.",
        "choice_a": "Vehicles are entering a parking garage.",
        "choice_b": "Clothes hangers are scattered on the ground.",
        "choice_c": "Empty racks are lined up next to a building.",
        "choice_d": "Clothing is being displayed under a tent.",
        "correct_choice": "D",
        "explanation": "Quần áo được trưng bày trên các giá treo bên dưới mái lều che ngoài trời.",
        "distractor_analysis": "[Bẫy Trạng Thái & Chi Tiết Giả] A (vehicles entering) sai vì không có xe đang di chuyển. B (hangers scattered) sai vì móc treo được xếp gọn gàng. C (empty racks) sai vì các giá treo đều đầy quần áo.",
        "paraphrase_pair": "displayed under a tent = exhibited beneath a canopy shelter",
        "image_url": "/part1/ets2024_01_q4.jpg",
        "audio_url": "/audio/ets2024_01/part1_q04.mp3",
        "lesson_number": 1,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 5,
        "sentence": "(A) Potted plants have been suspended from a ceiling. (B) Chairs have been stacked in front of an entryway. (C) A computer station has been set up on a desk. (D) A rug has been rolled up against a wall.",
        "choice_a": "Potted plants have been suspended from a ceiling.",
        "choice_b": "Chairs have been stacked in front of an entryway.",
        "choice_c": "A computer station has been set up on a desk.",
        "choice_d": "A rug has been rolled up against a wall.",
        "correct_choice": "C",
        "explanation": "Bộ máy vi tính (màn hình, bàn phím, chuột) đã được lắp đặt hoàn chỉnh trên bàn làm việc.",
        "distractor_analysis": "[Bẫy Giới Từ & Vị Trí Vật Thể] A (suspended from ceiling) bẫy từ 'potted plants' nhưng cây đặt trên bàn chứ không treo từ trần nhà. B (chairs stacked) ghế không bị xếp chồng. D (rug rolled up) không có thảm cuộn tròn.",
        "paraphrase_pair": "computer station set up on a desk = workstation assembled on a table",
        "image_url": "/part1/ets2024_01_q5.jpg",
        "audio_url": "/audio/ets2024_01/part1_q05.mp3",
        "lesson_number": 1,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 1",
        "question_no": 6,
        "sentence": "(A) One of the men is sweeping a patio. (B) One of the men is replacing some flooring. (C) A door has been taken off its frame. (D) A light fixture has been left on the ground.",
        "choice_a": "One of the men is sweeping a patio.",
        "choice_b": "One of the men is replacing some flooring.",
        "choice_c": "A door has been taken off its frame.",
        "choice_d": "A light fixture has been left on the ground.",
        "correct_choice": "C",
        "explanation": "Một cánh cửa gỗ đã được tháo rời khỏi khung và dựng nghiêng dựa vào bức tường gạch.",
        "distractor_analysis": "[Bẫy Hành Động Công Nhân] A (sweeping) không ai quét dọn. B (replacing flooring) không ai thay sàn gạch. D (light fixture on ground) không có đèn chiếu sáng nằm dưới đất.",
        "paraphrase_pair": "taken off its frame = removed from its hinges/doorframe",
        "image_url": "/part1/ets2024_01_q6.jpg",
        "audio_url": "/audio/ets2024_01/part1_q06.mp3",
        "lesson_number": 1,
    },

    # -------------------------------------------------------------
    # Part 2: Question - Response (Q7 - Q31)
    # -------------------------------------------------------------
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 7,
        "sentence": "How old is this building?",
        "choice_a": "To ship some materials.",
        "choice_b": "About ten years old.",
        "choice_c": "Company offices, I think.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Câu hỏi về tuổi thọ của tòa nhà ('How old...?'), đáp án B trả lời trực tiếp độ tuổi ('About ten years old').",
        "distractor_analysis": "[Bẫy Lạc Đề & Mục Đích] A trả lời cho câu hỏi mục đích 'Why/What for'. C trả lời cho câu hỏi 'What is it used for'.",
        "paraphrase_pair": "how old is this building = the age of the structure",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q07.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 8,
        "sentence": "Can you come to my jazz performance tonight?",
        "choice_a": "I'm sorry, I was late for the meeting.",
        "choice_b": "Mostly just local musicians.",
        "choice_c": "Sure, I'll be there!",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Lời mời tham dự buổi biểu diễn ('Can you come...?'), đáp án C nhận lời trực tiếp hào hứng ('Sure, I'll be there!').",
        "distractor_analysis": "[Bẫy Lạc Thì & Từ Cùng Trường Nghĩa] A dùng thì quá khứ 'was late' không khớp câu hỏi về 'tonight'. B dùng từ 'musicians' liên tưởng đến nhạc jazz nhưng không trả lời câu hỏi mời.",
        "paraphrase_pair": "can you come = are you able to attend",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q08.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 9,
        "sentence": "Which apartment submitted a work order?",
        "choice_a": "It's what you do for a living.",
        "choice_b": "Submit your assignment here.",
        "choice_c": "It came from the tenants in B23.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi 'Which apartment...' (Căn hộ nào...?), đáp án C chỉ rõ nguồn gốc yêu cầu bảo trì ('tenants in B23').",
        "distractor_analysis": "[Bẫy Lặp Từ Same Word] A bẫy từ 'living'/'work'. B bẫy lặp lại từ 'submit' trong câu hỏi nhưng sai hoàn toàn về ngữ cảnh 'assignment'.",
        "paraphrase_pair": "submitted a work order = filed a maintenance request",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q09.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 10,
        "sentence": "Will you contact the vendor about changing our delivery date?",
        "choice_a": "Of course, I'll take care of it.",
        "choice_b": "An email receipt.",
        "choice_c": "Could I get change for a dollar?",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Yêu cầu nhờ vả ('Will you contact...?'), đáp án A nhận lời xử lý công việc ('Of course, I'll take care of it').",
        "distractor_analysis": "[Bẫy Từ Đồng Âm 'Change'] C bẫy từ 'change' (tiền lẻ) so với 'changing' (thay đổi) trong đề bài. B là cụm danh từ cụt không trả lời cho câu hỏi hành động.",
        "paraphrase_pair": "take care of it = handle the task / reach out to the supplier",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q10.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 11,
        "sentence": "Why was the maintenance worker here?",
        "choice_a": "No, he didn't.",
        "choice_b": "From 3:00 until 4:00.",
        "choice_c": "Because the light needed to be fixed.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi lý do 'Why...', đáp án C giải thích nguyên nhân rõ ràng ('Because the light needed to be fixed').",
        "distractor_analysis": "[Bẫy Yes/No với Câu Hỏi Wh-] A là bẫy Yes/No cấm kỵ với câu hỏi 'Why'. B trả lời cho câu hỏi 'How long' hoặc 'When'.",
        "paraphrase_pair": "needed to be fixed = required repair",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q11.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 12,
        "sentence": "Did management make a hiring decision yet?",
        "choice_a": "Put it on the highest shelf.",
        "choice_b": "The personnel department.",
        "choice_c": "Yes, they chose Jacob Borgman.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi Yes/No xác nhận quyết định tuyển dụng, C xác nhận có và nêu rõ người được chọn ('chose Jacob Borgman').",
        "distractor_analysis": "[Bẫy Âm Tương Đồng Similar Sound] A bẫy từ 'highest' nghe na ná 'hiring'. B bẫy từ liên tưởng nhân sự ('personnel') nhưng không trả lời việc đã có quyết định hay chưa.",
        "paraphrase_pair": "make a hiring decision = select a candidate",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q12.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 13,
        "sentence": "Do you want to eat here in our cafeteria or go out?",
        "choice_a": "He went there yesterday.",
        "choice_b": "Well, maybe a sandwich.",
        "choice_c": "Let's eat here.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi lựa chọn 'eat here... or go out?', đáp án C chọn trực tiếp một trong hai phương án ('Let's eat here').",
        "distractor_analysis": "[Bẫy Lạc Chủ Ngữ & Thì] A dùng chủ ngữ 'He' và quá khứ 'went' trong khi câu hỏi hỏi 'you' và thì hiện tại. B nói về món ăn ('sandwich') chứ không chọn địa điểm ăn.",
        "paraphrase_pair": "eat here = dine in our cafeteria",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q13.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 14,
        "sentence": "Didn't you email the employment contract to Mr. Patel yesterday?",
        "choice_a": "Yes, I would agree.",
        "choice_b": "No, I'll send it now.",
        "choice_c": "Check the employee manual.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Câu hỏi phủ định quá khứ xác nhận việc gửi hợp đồng, B thừa nhận chưa gửi và sẽ gửi ngay lập tức ('No, I'll send it now').",
        "distractor_analysis": "[Bẫy Trả Lời Sai Ngữ Cảnh] A là câu đồng tình quan điểm ('I would agree') không dùng để trả lời hành động thực tế. C bẫy từ 'employee' liên tưởng đến 'employment'.",
        "paraphrase_pair": "send it now = dispatch the contract immediately",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q14.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 15,
        "sentence": "Our division's picnic is this Saturday, right?",
        "choice_a": "There's a lot of rain in the forecast.",
        "choice_b": "Sure, I like salad.",
        "choice_c": "At the end of this corridor.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Câu hỏi đuôi xác nhận buổi dã ngoại, A đưa ra câu trả lời gián tiếp: Dự báo thời tiết có nhiều mưa (ngụ ý có thể bị hoãn hoặc hủy).",
        "distractor_analysis": "[Bẫy Trả Lời Trực Tiếp Giả Tạo] B bẫy từ liên tưởng 'picnic -> salad'. C trả lời cho câu hỏi địa điểm 'Where'.",
        "paraphrase_pair": "rain in the forecast = inclement weather expected",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q15.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 16,
        "sentence": "Would you like coffee or tea?",
        "choice_a": "Just water, please.",
        "choice_b": "For a few dollars more.",
        "choice_c": "A 15-minute break.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Câu hỏi lựa chọn đồ uống, đáp án A đưa ra phương án thay thế lịch sự ('Just water, please').",
        "distractor_analysis": "[Bẫy Lạc Ngữ Cảnh] B bẫy về giá cả tiền nong. C bẫy từ liên tưởng 'coffee break' nhưng dùng sai nghĩa.",
        "paraphrase_pair": "just water = an alternative beverage preference",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q16.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 17,
        "sentence": "We achieved our sales targets this month.",
        "choice_a": "That's excellent news!",
        "choice_b": "A few times a day.",
        "choice_c": "To the end of April.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Câu trần thuật thông báo thành tích doanh số, đáp án A phản hồi chúc mừng hào hứng ('That's excellent news!').",
        "distractor_analysis": "[Bẫy Tần Suất & Thời Gian] B trả lời cho 'How often'. C trả lời cho 'Until when'.",
        "paraphrase_pair": "achieved our sales targets = met the revenue goals",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q17.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 18,
        "sentence": "How often do you travel for your job?",
        "choice_a": "It turned out well.",
        "choice_b": "Yes, I did find one.",
        "choice_c": "About once a month.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi tần suất 'How often...', đáp án C trả lời tần suất chính xác ('About once a month').",
        "distractor_analysis": "[Bẫy Yes/No] B trả lời Yes/No cho câu hỏi 'How often' là hoàn toàn sai. A trả lời cho kết quả của một sự việc.",
        "paraphrase_pair": "about once a month = monthly business trips",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q18.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 19,
        "sentence": "We should hike the Wildflower Trail today.",
        "choice_a": "This seat is available.",
        "choice_b": "I didn't bring boots.",
        "choice_c": "At the visitor center.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Lời đề nghị đi leo núi dã ngoại, B đưa ra lý do từ chối gián tiếp: Tôi không mang theo giày leo núi chuyên dụng.",
        "distractor_analysis": "[Bẫy Từ Liên Tưởng] C bẫy địa điểm 'trail -> visitor center' nhưng không phản hồi lời đề nghị. A nói về chỗ ngồi không liên quan.",
        "paraphrase_pair": "didn't bring boots = unprepared for hiking outdoor trails",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q19.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 20,
        "sentence": "You have booked a hotel in London, haven't you?",
        "choice_a": "Very enjoyable, thanks.",
        "choice_b": "He usually takes the train.",
        "choice_c": "Yes, I made a reservation last week.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Câu hỏi đuôi xác nhận việc đặt phòng, C khẳng định đã đặt từ tuần trước ('made a reservation last week').",
        "distractor_analysis": "[Bẫy Chủ Ngữ & Lệch Thì] B dùng chủ ngữ 'He' sai người. A trả lời trải nghiệm chuyến đi đã kết thúc.",
        "paraphrase_pair": "booked a hotel = made an accommodation reservation",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q20.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 21,
        "sentence": "Are there any tickets left for tonight's concert?",
        "choice_a": "It's sold out.",
        "choice_b": "He's a concert violinist.",
        "choice_c": "They already left.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Hỏi xem còn vé hòa nhạc tối nay không, A thông báo tình trạng hết vé ('It's sold out').",
        "distractor_analysis": "[Bẫy Từ Đồng Âm & Cùng Gốc] B bẫy lặp lại từ 'concert'. C bẫy từ 'left' (rời đi) so với 'left' (còn lại) trong đề bài.",
        "paraphrase_pair": "sold out = no tickets remaining",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q21.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 22,
        "sentence": "Haven't you used this software before?",
        "choice_a": "Can I take your order?",
        "choice_b": "I haven't had the chance.",
        "choice_c": "About forty dollars.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Câu hỏi phủ định hỏi về kinh nghiệm dùng phần mềm, B trả lời chưa có cơ hội thử nghiệm ('haven't had the chance').",
        "distractor_analysis": "[Bẫy Ngữ Cảnh Nhà Hàng / Giá Cả] A là câu hỏi bồi bàn trong nhà hàng. C là giá tiền.",
        "paraphrase_pair": "haven't had the chance = have not had the opportunity yet",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q22.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 23,
        "sentence": "When is the new blender going to be released?",
        "choice_a": "Only with fruits and vegetables.",
        "choice_b": "In the kitchen cabinet.",
        "choice_c": "The prototype is still being tested.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Hỏi về thời điểm ra mắt máy xay mới, C trả lời gián tiếp: Bản mẫu vẫn đang được thử nghiệm (ngụ ý chưa ấn định ngày ra mắt).",
        "distractor_analysis": "[Bẫy Địa Điểm & Chức Năng] A bẫy công dụng của máy xay ('fruits and vegetables'). B trả lời câu hỏi vị trí 'Where'.",
        "paraphrase_pair": "still being tested = undergoing product evaluation before launch",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q23.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 24,
        "sentence": "Who's picking up our clients at the airport?",
        "choice_a": "They decided to drive.",
        "choice_b": "At Terminal 2.",
        "choice_c": "It's a marketing position.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Hỏi ai đi đón khách hàng tại sân bay, A trả lời gián tiếp: Khách hàng quyết định tự lái xe (nghĩa là không ai cần phải đi đón).",
        "distractor_analysis": "[Bẫy Địa Điểm Sân Bay] B bẫy địa điểm 'Terminal 2' trả lời cho 'Where'. C bẫy từ 'position' không liên quan.",
        "paraphrase_pair": "decided to drive = renting a car / traveling independently",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q24.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 25,
        "sentence": "Where are the red roses that came in this morning?",
        "choice_a": "About three liters of water.",
        "choice_b": "No, I didn't check out the sale.",
        "choice_c": "I needed some for a large bouquet.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Hỏi hoa hồng đỏ mới nhập sáng nay để ở đâu, C giải thích gián tiếp: Tôi cần một ít để cắm một bó hoa lớn (ngụ ý đã lấy đi).",
        "distractor_analysis": "[Bẫy Yes/No với Where] B trả lời No cho câu hỏi Where là sai. A trả lời lượng nước 'How much'.",
        "paraphrase_pair": "needed some for a large bouquet = used them for floral arrangement",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q25.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 26,
        "sentence": "This film has been nominated for several awards.",
        "choice_a": "Why don't we go see it?",
        "choice_b": "After the announcement.",
        "choice_c": "He made a great speech.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Câu trần thuật khen ngợi bộ phim được đề cử nhiều giải thưởng, A rủ đi xem phim ngay ('Why don't we go see it?').",
        "distractor_analysis": "[Bẫy Từ Liên Tưởng Lễ Trao Giải] C bẫy 'speech' (bài phát biểu nhận giải). B bẫy 'announcement' (công bố giải).",
        "paraphrase_pair": "why don't we go see it = let's watch the movie",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q26.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 27,
        "sentence": "Who's interested in starting a carpool program?",
        "choice_a": "Thanks, but I can't swim.",
        "choice_b": "Clara's already organizing one.",
        "choice_c": "It's a very interesting article.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Hỏi ai quan tâm đến việc lập nhóm đi chung xe (carpool), B thông báo Clara đã đang đứng ra tổ chức rồi.",
        "distractor_analysis": "[Bẫy Từ Đồng Âm & Cùng Gốc] A bẫy từ 'pool' trong 'carpool' thành 'bể bơi' (swimming pool). C bẫy lặp lại từ 'interesting' so với 'interested'.",
        "paraphrase_pair": "organizing one = coordinating a rideshare scheme",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q27.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 28,
        "sentence": "Where will I teach my workshop this month?",
        "choice_a": "We just sent an email to all instructors.",
        "choice_b": "Five to seven months.",
        "choice_c": "Yes, it's a beautiful building.",
        "choice_d": None,
        "correct_choice": "A",
        "explanation": "Hỏi địa điểm dạy hội thảo tháng này ở đâu, A trả lời gián tiếp: Chúng tôi vừa gửi email thông báo tới toàn bộ giảng viên (hướng dẫn kiểm tra hộp thư).",
        "distractor_analysis": "[Bẫy Lặp Từ 'Month' & Yes/No] B bẫy lặp lại từ 'months' nhưng trả lời khoảng thời gian. C trả lời Yes cho câu hỏi 'Where' là sai.",
        "paraphrase_pair": "sent an email = details provided via message",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q28.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 29,
        "sentence": "Why are we moving these sweaters to the back of the store?",
        "choice_a": "In the new shopping mall.",
        "choice_b": "Yes, they come in other colors.",
        "choice_c": "Our spring merchandise is arriving soon.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Hỏi lý do chuyển áo len ra phía sau cửa hàng, C giải thích: Hàng mùa xuân sắp về (áo len mùa đông cần nhường chỗ cho hàng mới).",
        "distractor_analysis": "[Bẫy Yes/No & Địa Điểm] B trả lời Yes cho câu hỏi 'Why' là sai. A trả lời cho câu hỏi 'Where'.",
        "paraphrase_pair": "spring merchandise is arriving = new seasonal stock is coming in",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q29.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 30,
        "sentence": "Would you be interested in working on some of these contracts?",
        "choice_a": "Thank you for meeting me.",
        "choice_b": "A contact lens prescription.",
        "choice_c": "I have very limited time.",
        "choice_d": None,
        "correct_choice": "C",
        "explanation": "Đề nghị hỗ trợ xử lý hợp đồng, C từ chối gián tiếp: Tôi có rất ít thời gian (đang quá bận).",
        "distractor_analysis": "[Bẫy Âm Tương Đồng Similar Sound] B bẫy từ 'contact' phát âm rất giống 'contract'. A là câu chào hỏi lịch sự không trả lời cho câu hỏi công việc.",
        "paraphrase_pair": "have very limited time = tight schedule / overloaded with work",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q30.mp3",
        "lesson_number": 2,
    },
    {
        "test_id": "ETS2024_01",
        "part": "Part 2",
        "question_no": 31,
        "sentence": "What type of job are you looking for?",
        "choice_a": "No, at 10:00 A.M.",
        "choice_b": "I really like working with computers.",
        "choice_c": "Just a resume as needed.",
        "choice_d": None,
        "correct_choice": "B",
        "explanation": "Hỏi về loại công việc đang tìm kiếm ('What type of job...?'), B trả lời sở thích chuyên môn ('working with computers' - kỹ sư phần mềm / CNTT).",
        "distractor_analysis": "[Bẫy Yes/No & Thời Gian] A trả lời No và giờ giấc là sai hoàn toàn với câu hỏi 'What type'. C bẫy từ liên tưởng tuyển dụng 'resume' nhưng không chỉ ngành nghề.",
        "paraphrase_pair": "working with computers = software engineering / IT roles",
        "image_url": None,
        "audio_url": "/audio/ets2024_01/part2_q31.mp3",
        "lesson_number": 2,
    },
]


def ingest():
    init_db()
    db = SessionLocal()
    try:
        mock = db.query(MockTest).filter_by(test_id="ETS2024_01").first()
        if not mock:
            mock = MockTest(
                test_id="ETS2024_01",
                name="ETS TOEIC Regular Test 2024 - Test 01",
                year=2024,
                publisher="ETS",
                total_questions=200,
            )
            db.add(mock)
            db.commit()

        # Remove previous legacy/placeholder questions for Part 1 (Q1-Q6) and Part 2 (Q7-Q31)
        part1_nos = list(range(1, 7))
        part2_nos = list(range(7, 32))

        db.query(TestQuestion).filter(
            TestQuestion.test_id == "ETS2024_01",
            TestQuestion.part == "Part 1",
            TestQuestion.question_no.in_(part1_nos)
        ).delete(synchronize_session=False)

        db.query(TestQuestion).filter(
            TestQuestion.test_id == "ETS2024_01",
            TestQuestion.part == "Part 2",
            TestQuestion.question_no.in_(part2_nos)
        ).delete(synchronize_session=False)

        db.commit()

        inserted = 0
        for item in AUTHENTIC_TEST01_LISTENING:
            q = TestQuestion(
                test_id=item["test_id"],
                part=item["part"],
                question_no=item["question_no"],
                sentence=item["sentence"],
                choice_a=item["choice_a"],
                choice_b=item["choice_b"],
                choice_c=item["choice_c"],
                choice_d=item["choice_d"],
                correct_choice=item["correct_choice"],
                explanation=item["explanation"],
                distractor_analysis=item["distractor_analysis"],
                paraphrase_pair=item["paraphrase_pair"],
                image_url=item["image_url"],
                audio_url=item["audio_url"],
                lesson_number=item.get("lesson_number"),
                source="ets_official",
                created_at=utcnow(),
            )
            db.add(q)
            inserted += 1

        db.commit()
        print(f"✓ Ingested {inserted} authentic ETS 2024 Test 01 Listening questions (Part 1: 6, Part 2: 25)")

    except Exception as e:
        db.rollback()
        print(f"Error during ingestion: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    ingest()
